server:
  port: 8800 #???

spring:
  application:
    name: springcloud-stream-consumer

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit

  cloud:
    stream:
      bindings:
        myInput:
          destination: stream-test

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka/,http://localhost:8301/eureka/


